### ISSUE TITLE
I can not build ThaliDeviceHub

### ISSUE THREAD

**Issue by demonister** [thaliproject/thali#70]
> git clone https://git01.codeplex.com/thali
> cd thali/Production/ThaliDeviceHub/android/android/
> ./gradlew assembleDebug

and i have

:android:preBuild
:android:compileDebugNdk UP-TO-DATE
:android:preDebugBuild
:android:checkDebugManifest
:android:preReleaseBuild
:android:prepareComCouchbaseLiteCouchbaseLiteAndroid100Beta3rc11Library UP-TO-DATE
:android:prepareComMsopentechThaliThaliOnionProxyAndroid000Library UP-TO-DATE
:android:prepareComMsopentechThaliThaliUtilitiesAndroid002Library UP-TO-DATE
:android:prepareDebugDependencies
:android:compileDebugAidl UP-TO-DATE
:android:compileDebugRenderscript UP-TO-DATE
:android:generateDebugBuildConfig UP-TO-DATE
:android:mergeDebugAssets UP-TO-DATE
:android:generateDebugResValues UP-TO-DATE
:android:generateDebugResources UP-TO-DATE
:android:mergeDebugResources UP-TO-DATE
:android:processDebugManifest UP-TO-DATE
:android:processDebugResources UP-TO-DATE
:android:generateDebugSources UP-TO-DATE
:android:compileDebugJava
/home/demonister/work/android/thali/Production/ThaliDeviceHub/android/android/src/main/java/com/msopentech/thali/devicehub/android/ThaliDeviceHubService.java:75: error: incompatible types: AndroidOnionProxyManager cannot be converted to Proxy
                    androidOnionProxyManager);
                    ^
/home/demonister/work/android/thali/Production/ThaliDeviceHub/android/android/src/main/java/com/msopentech/thali/devicehub/android/ThaliDeviceHubService.java:107: error: cannot find symbol
                    httpKeysIntent.putExtra(OnionHttpKeyURLName, thaliListener.getHttpKeys().getOnionHttpKeyURL());
                                                                                            ^
  symbol:   method getOnionHttpKeyURL()
  location: class HttpKeyTypes

**Comment by demonister** [comment]
Error:A problem occurred configuring project ':android'.

> Could not resolve all dependencies for configuration ':android:_debugCompile'.
> Could not resolve Production.Utilities:ThaliUtilitiesUniversal:unspecified.
>      Required by:
>          android:android:unspecified > com.msopentech.thali:ThaliTDHUniversal:0.0.2
>          android:android:unspecified > com.msopentech.thali:ThaliUtilitiesAndroid:0.0.2
>       > java.lang.NullPointerException (no error message)
> Could not resolve com.couchbase.lite:couchbase-lite-android:1.0.0-beta3rc1.
>      Required by:
>          android:android:unspecified > com.msopentech.thali:ThaliUtilitiesAndroid:0.0.2
>       > java.lang.NullPointerException (no error message)

**Comment by yaronyg** [comment]
So there are two different problems here but I strongly suspect they are related. The core issue is that right now to build the Android TDH one has to have already built on one's machine 14 different dependencies. :(

The reason for this is that we have not yet set up Maven in any sane way so you could just download rather than build dependencies. @jpoon is right now working on the Jenkins scripts needed to build and deploy all of our dependencies to maven. Also, in the future, unless you are working on Thali, you won't need to build the TDH. We will actually give out binaries for Android and all the desktop platforms. This is part of the work that @jpoon is finishing up.

But it's going to likely be several weeks before this is all ready. So in the meantime if you want to build the Android TDH then I would suggest going over to http://www.thaliproject.org/mediawiki/index.php?title=Developer_Handbook (which I just updated massively) and give it a read. The key part is http://www.thaliproject.org/mediawiki/index.php?title=Developer_Handbook#Using_the_global_build_script_to_build_the_TDH. That is our global build script that builds everything.

I do apologize for how painful everything is right now. We are actively working on getting Jenkins set up to make it vastly better.

**Comment by jpoon** [comment]
If you are building everything from scratch, you'll also need to setup your machine to install a couple other dependencies (Android SDK, JDK, etc). 
- Linux: You can use the following install scripts (based on ubuntu) to install all the dependencies: https://gist.github.com/jpoon/d58adf08aa5d2ad87e30.
- Windows: More manual process than Linux. Things to install are listed here: https://gist.github.com/jpoon/39ab4f3692147758d629 (you can ignore all the Jenkins slave commands).

Once you have all the above,  follow the instructions on the wiki provided above by @yaronyg  and you should be good to go. 

As @yaronyg mentioned, once we setup our artifactory, thing should be a lot cleaner.

**Comment by yaronyg** [comment]
Builds fine now.
