### ISSUE TITLE
Write a OpenSSL C to Node.js Bridge

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/thali#99]
Once we figure out which OpenSSL APIs we need (see #98) then we need to create a Node.js API to wrap those calls and expose them as a native Add-On.

**Comment by srichal** [comment]
Tried to create an Addon so that a c/c++ function can be called by Node. Hit a road block and decided not to continue with this approach as Addons in JXcore is different from Node.

Sent out an email to Oguz (JXcore guy) explaining what we are trying to achieve and asked him what approach to take in JXcore.

While waiting for response/support from JXcore, will investigate openssl in Node and see how far we can go to achieve our goal of creating/passing/verifying certificates.

**Comment by srichal** [comment]
Opened issue #152 to investigate openssl in Node.

**Comment by srichal** [comment]
Investigated/closed issue #152 and concluded that it is better to write our own JS API to generate the required PKCS12 container.

Sent a couple of detailed emails to Oguz about how to write the C-to-JS bridge in JXcore.

**Comment by srichal** [comment]
Oguz created a fork of jxcore at "https://github.com/thaliproject/jxcore-for-thali.git". Here, he created a custom wrap (file/function in CPP) which can be compiled into the jxcore executable.

I expanded this custom wrap to include my code which creates an openssl X509 certificate file. I then compiled jxcore to generate the executable "jx" which includes the custom wrap. I was finally able to call the custom wrap CPP function inside JS code. I was able to test the creation of the certificate file by executing JS code which calls the custom wrap function.
